stages:
  - build

trigger_testbed:
  stage: build
  image:
    name: registry.gitlab.sensirion.lokal/sensirion/docker/docker-ubuntu:18.04-1.0.0
  tags:
    - docker
    - linux
  script:
  - >
    curl
    --request POST
    --form token=$CI_JOB_TOKEN
    --form ref=sts-test
    --form  "variables[SENSOR_TYPE]=sts"
    --form  "variables[SENSOR_BRANCH]=$CI_COMMIT_REF_NAME"
    https://gitlab/api/v4/projects/801/trigger/pipeline
